import { DateTime } from 'luxon'
import { BaseModel, column, SnakeCaseNamingStrategy } from '@adonisjs/lucid/orm'
import type { StlCategory, StlDifficulty, StlMaterial } from '../../types/stl_library.js'
import { isMetadataComplete as classifyIsMetadataComplete } from '../../util/file_classification.js'

/**
 * Workshop / Offline STL Library catalog entry.
 *
 * One row per file on disk. Created/updated by StlScannerService when it
 * walks ${NOMAD_DATA_ROOT}/storage/stl-library/. The filesystem is the
 * source of truth — if a file is deleted from disk, its row is removed on
 * the next scan. If a file appears, a row is inserted with metadata_pending
 * set true. Users complete metadata via the Workshop UI; that flips
 * metadata_pending false.
 */
export default class StlFile extends BaseModel {
  static table = 'stl_files'
  static namingStrategy = new SnakeCaseNamingStrategy()

  @column({ isPrimary: true })
  declare id: number

  /**
   * Path relative to ${NOMAD_DATA_ROOT}/storage/stl-library/.
   * Example: "medical/finger-splint-large.stl"
   */
  @column()
  declare path: string

  @column()
  declare name: string

  @column()
  declare category: StlCategory

  /**
   * File-type discriminator. Populated at index time by classifyFileType().
   * All pre-broadening rows default to 'stl' via the migration column default.
   */
  @column()
  declare file_type: string

  /**
   * JSON column stored as a string array in MySQL. Adonis Lucid serializes
   * arrays/objects via prepare/consume — declared with a `prepare` and
   * `consume` so callers always see/set a string[] (or null), never a
   * stringified JSON blob.
   *
   * Consume tolerates empty strings + invalid JSON: some rows ended up with
   * tags='' (empty string) instead of NULL, which would crash JSON.parse
   * and 500 the entire /workshop page on read. Defensive consume returns
   * null on any non-array result so a single bad row can't break the list.
   */
  @column({
    prepare: (value: string[] | null) => (value === null ? null : JSON.stringify(value)),
    consume: (value: string | null) => {
      if (value === null || value === '') return null
      try {
        const parsed = JSON.parse(value)
        return Array.isArray(parsed) ? (parsed as string[]) : null
      } catch {
        return null
      }
    },
  })
  declare tags: string[] | null

  @column()
  declare material: StlMaterial | null

  @column()
  declare print_time_minutes: number | null

  @column()
  declare infill_pct: number | null

  @column()
  declare difficulty: StlDifficulty | null

  @column()
  declare description: string | null

  @column()
  declare source_url: string | null

  /**
   * Freeform license/rights note. No required value — see the Workshop
   * "rights acknowledged" flag in kv_store for the user-level gate.
   */
  @column()
  declare license: string | null

  /**
   * Relative path to a 256×256 PNG generated by stl-thumb on index.
   * Null if generation hasn't run yet OR if the renderer failed
   * (in which case thumbnail_failed is true and the UI shows a generic
   * SVG icon instead of retrying on every page load).
   */
  @column()
  declare thumbnail_path: string | null

  @column()
  declare thumbnail_failed: boolean

  /**
   * Extracted text from the first 5 pages of a PDF (pdf-parse).
   * NULL for non-PDF rows and for PDFs where extraction failed or hasn't
   * run yet. Capped at 20 KB stored. Populated by StlScannerService at
   * scan time for file_type='pdf' rows.
   */
  @column()
  declare pdf_text_extract: string | null

  @column()
  declare file_size_bytes: number

  /**
   * SHA-256 of the first 1 MB of the file. Lets the scanner skip
   * re-hashing on files whose size + first-1MB haven't changed —
   * meaningful for libraries with 50+ MB STLs.
   */
  @column()
  declare file_hash: string | null

  @column()
  declare metadata_pending: boolean

  @column.dateTime({ autoCreate: true, columnName: 'added_at' })
  declare added_at: DateTime

  @column.dateTime({ autoCreate: true, autoUpdate: true, columnName: 'last_indexed_at' })
  declare last_indexed_at: DateTime

  /**
   * Required-metadata check. Thin wrapper over the pure
   * `isMetadataComplete` helper in util/file_classification.ts so the
   * model API stays stable for existing callers (controller, scanner).
   *
   * Callers that have a `file_type` on the row automatically get the
   * type-aware logic (stl → strict; cad/pdf/image → name only). When the
   * caller passes a row without `file_type` (old call-sites that only pass
   * name/material/print_time/difficulty), we default to 'stl' to preserve
   * the existing strict behaviour.
   */
  static isMetadataComplete(row: {
    file_type?: string | null
    name?: string | null
    material?: StlMaterial | null
    print_time_minutes?: number | null
    difficulty?: StlDifficulty | null
  }): boolean {
    return classifyIsMetadataComplete({
      file_type: row.file_type ?? 'stl',
      name: row.name,
      material: row.material,
      print_time_minutes: row.print_time_minutes,
      difficulty: row.difficulty,
    })
  }
}
