.Dd 2026-06-02
.Dt NOMAD-BUILD-STATUS 1
.Os
.Sh NAME
.Nm nomad-build-status
.Nd alias for nomad build-check
.Sh SYNOPSIS
.Nm nomad build-status
.Sh DESCRIPTION
.Nm nomad build-status
is an alias for
.Ic nomad build-check .
See
.Xr nomad-build-check 1
for the full description.
.Sh SEE ALSO
.Xr nomad-build-check 1 ,
.Xr nomad-upgrade 1
