export const SERVICE_NAMES = {
  KIWIX: 'nomad_kiwix_server',
  OLLAMA: 'nomad_ollama',
  QDRANT: 'nomad_qdrant',
  CYBERCHEF: 'nomad_cyberchef',
  FLATNOTES: 'nomad_flatnotes',
  KOLIBRI: 'nomad_kolibri',
  GROCY: 'nomad_grocy',
  MESHTASTIC_WEB: 'nomad_meshtastic_web',
  MESHCORE_WEB: 'nomad_meshcore_web',
  MESH: 'nomad_mesh',
  VAULTWARDEN: 'nomad_vaultwarden',
  STIRLING_PDF: 'nomad_stirling_pdf',
  IT_TOOLS: 'nomad_it_tools',
  EXCALIDRAW: 'nomad_excalidraw',
  CALIBRE_WEB: 'nomad_calibre_web',
}
