import { BaseSchema } from '@adonisjs/lucid/schema'

/**
 * Workshop / Offline STL Library — file catalog.
 *
 * Indexes 3D-printable files (.stl, .3mf) that live on disk under
 * ${NOMAD_DATA_ROOT}/storage/stl-library/. The filesystem is the source of
 * truth; this table is a queryable index built by StlScannerService.
 *
 * Categories, materials, and difficulty values come from the constants in
 * types/stl_library.ts. Enforced as varchars (not native enums) to keep the
 * migration portable across MySQL versions and to allow adding values
 * without an ALTER TABLE on the column.
 *
 * On first scan, files appear with metadata_pending=true and minimal data
 * (name=filename, category inferred from parent dir, everything else null).
 * Users must fill name + material + print_time_minutes + difficulty in the
 * UI before metadata_pending flips false and the file appears in normal
 * grid views (pending files visible only via the "Needs metadata" filter).
 */
export default class extends BaseSchema {
  protected tableName = 'stl_files'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.bigIncrements('id').primary()

      // Path relative to the library root. Unique per file — re-indexing the
      // same path is an upsert, not a duplicate insert.
      table.string('path', 512).notNullable().unique()

      table.string('name', 255).notNullable()

      table.string('category', 32).notNullable().defaultTo('other')

      // JSON array of tag strings. MySQL 5.7+ + MariaDB 10.2+ support JSON.
      table.json('tags').nullable()

      // Nullable until the user fills it in. Constraints enforced at the
      // model/validator layer, not the DB, so we can evolve the enum
      // without ALTER TABLE.
      table.string('material', 16).nullable()
      table.integer('print_time_minutes').nullable()
      table.integer('infill_pct').nullable()  // 0..100
      table.string('difficulty', 16).nullable()

      table.text('description').nullable()
      table.string('source_url', 512).nullable()

      // Freeform — CC0, CC-BY-4.0, public-domain, "my own work", or anything
      // else. No required value. The global Workshop rights acknowledgment in
      // kv_store handles "do you have the right to store this" at the user
      // level, not per file.
      table.string('license', 255).nullable()

      // Generated by stl-thumb during the scan, relative to library root.
      // thumbnail_failed is a sticky flag so we don't burn CPU retrying
      // unreadable files on every rescan.
      table.string('thumbnail_path', 512).nullable()
      table.boolean('thumbnail_failed').notNullable().defaultTo(false)

      table.bigInteger('file_size_bytes').notNullable().defaultTo(0)

      // SHA-256 of the first 1 MB of the file. Fast change-detect on
      // rescan without re-hashing 50 MB STL files on every pass.
      table.string('file_hash', 64).nullable()

      // True until the user fills required metadata via the UI.
      table.boolean('metadata_pending').notNullable().defaultTo(true)

      table.timestamp('added_at').notNullable()
      table.timestamp('last_indexed_at').notNullable()

      // Indexes that match the grid filters in the Workshop list page.
      table.index('category', 'idx_stl_files_category')
      table.index('material', 'idx_stl_files_material')
      table.index('difficulty', 'idx_stl_files_difficulty')
      table.index('metadata_pending', 'idx_stl_files_pending')
      table.index(['category', 'metadata_pending'], 'idx_stl_files_category_pending')
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
