import { promises as fs, createReadStream, existsSync } from 'node:fs'
import { join, relative, dirname, basename, extname } from 'node:path'
import { createHash } from 'node:crypto'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { DateTime } from 'luxon'
import logger from '@adonisjs/core/services/logger'
import StlFile from '#models/stl_file'
import { STL_CATEGORIES, type StlCategory } from '../../types/stl_library.js'
import {
  INDEXABLE_EXTS,
  classifyFileType,
  CATEGORY_REMAP,
  type WorkshopFileType,
} from '../../util/file_classification.js'

const execFileAsync = promisify(execFile)

/**
 * Workshop / Offline STL Library — filesystem scanner.
 *
 * Walks `${NOMAD_DATA_ROOT}/storage/stl-library/` and keeps the `stl_files`
 * table aligned with what's actually on disk:
 *   • New files on disk → inserted with metadata_pending=true
 *   • Changed files (size or first-1MB hash differs) → row updated, thumbnail
 *     invalidated so it regenerates on the next thumbnail pass
 *   • Files missing from disk → DB row deleted
 *
 * Thumbnails are generated by the `stl-thumb` binary (bundled in the admin
 * Docker image, see Dockerfile). Failed renders set thumbnail_failed=true
 * so we don't burn CPU retrying unreadable files on every scan.
 *
 * Triggered by:
 *   • The ace command `node ace stl:reindex` (manual, from CLI or cron-like)
 *   • The Workshop UI's "Rescan library" button (via controller)
 *   • Implicit: after `nomad stl import <dir>` finishes copying files in
 */
export class StlScannerService {
  /**
   * Library root inside the admin container.
   *
   * Compose mounts `${NOMAD_DATA_ROOT}/storage:/app/storage` (see
   * install/macos/compose.yaml line 47). So the in-container path for the
   * STL library is `/app/storage/stl-library`, NOT `/storage/stl-library`.
   *
   * Earlier versions of this constant were `/storage/stl-library` and
   * caused the controller's drive-detect to fail with "Workshop unavailable"
   * even when the data drive WAS mounted and the directory existed on the
   * host. Chris caught this 2026-05-11 — Workshop page showed the
   * unavailable panel right after a fresh install where the install step
   * had already created the directory under ${NOMAD_DATA_ROOT}/storage/.
   */
  public static readonly LIBRARY_ROOT = '/app/storage/stl-library'

  /**
   * Subdirectory inside the library root where generated PNG thumbnails live.
   * Prefixed with a dot so the recursive walk skips it naturally.
   */
  public static readonly THUMBNAIL_DIR = '.thumbnails'

  /**
   * File extensions we index — imported from the pure file_classification
   * helper so the scanner and the upload controller stay in sync automatically.
   * Covers stl, 3mf, cad (step/stp/dxf/dwg/f3d/scad), pdf, and images.
   */
  private static readonly INDEXABLE_EXTS = INDEXABLE_EXTS

  /**
   * Read up to this many bytes from the head of each file when computing the
   * change-detection hash. 1 MB is enough to detect "user re-exported the
   * same name with different geometry" without rehashing 50 MB STLs.
   */
  private static readonly HASH_BYTES = 1024 * 1024

  /**
   * Public entry point — full scan. Returns counts so the caller (ace
   * command or controller) can render a summary.
   */
  async scan(): Promise<ScanResult> {
    if (!existsSync(StlScannerService.LIBRARY_ROOT)) {
      logger.warn(
        `[StlScannerService] Library root missing at ${StlScannerService.LIBRARY_ROOT} — ` +
          'data drive likely disconnected. Skipping scan.'
      )
      return {
        available: false,
        added: 0,
        updated: 0,
        unchanged: 0,
        orphaned: 0,
        thumbnails_generated: 0,
        thumbnails_failed: 0,
      }
    }

    // Make sure the thumbnail dir exists. Created lazily so we don't fight
    // the drive's permissions on every empty library.
    await fs.mkdir(join(StlScannerService.LIBRARY_ROOT, StlScannerService.THUMBNAIL_DIR), {
      recursive: true,
    })

    const onDiskPaths = await this.walkLibrary()
    logger.info(`[StlScannerService] found ${onDiskPaths.length} indexable file(s) on disk`)

    let added = 0
    let updated = 0
    let unchanged = 0

    for (const absPath of onDiskPaths) {
      const relPath = relative(StlScannerService.LIBRARY_ROOT, absPath)
      const result = await this.upsertOne(absPath, relPath)
      if (result === 'added') added++
      else if (result === 'updated') updated++
      else unchanged++
    }

    const orphaned = await this.removeOrphans(onDiskPaths)

    const { generated, failed } = await this.generateThumbnails()

    return {
      available: true,
      added,
      updated,
      unchanged,
      orphaned,
      thumbnails_generated: generated,
      thumbnails_failed: failed,
    }
  }

  /**
   * Targeted scan for a specific set of absolute paths — used by the Workshop
   * upload flow, which just wrote the files to disk and wants them indexed
   * with thumbnails without walking the entire library or sweeping orphans.
   *
   * Returns a ScanResult shaped like `scan()` for caller convenience; `orphaned`
   * is always 0 because this path does not own the orphan-detection contract.
   *
   * Any input path that doesn't live under LIBRARY_ROOT is silently dropped
   * (defense in depth — the caller already builds these paths inside the
   * library, but we never want to index something outside the root).
   */
  async scanPaths(absPaths: string[]): Promise<ScanResult> {
    if (!existsSync(StlScannerService.LIBRARY_ROOT)) {
      return {
        available: false,
        added: 0,
        updated: 0,
        unchanged: 0,
        orphaned: 0,
        thumbnails_generated: 0,
        thumbnails_failed: 0,
      }
    }

    await fs.mkdir(join(StlScannerService.LIBRARY_ROOT, StlScannerService.THUMBNAIL_DIR), {
      recursive: true,
    })

    const rootWithSep = StlScannerService.LIBRARY_ROOT.endsWith('/')
      ? StlScannerService.LIBRARY_ROOT
      : StlScannerService.LIBRARY_ROOT + '/'

    let added = 0
    let updated = 0
    let unchanged = 0

    for (const absPath of absPaths) {
      if (!absPath.startsWith(rootWithSep)) {
        logger.warn(`[StlScannerService] scanPaths skipped non-library path: ${absPath}`)
        continue
      }
      if (!existsSync(absPath)) {
        logger.warn(`[StlScannerService] scanPaths skipped missing path: ${absPath}`)
        continue
      }
      const relPath = relative(StlScannerService.LIBRARY_ROOT, absPath)
      const result = await this.upsertOne(absPath, relPath)
      if (result === 'added') added++
      else if (result === 'updated') updated++
      else unchanged++
    }

    const { generated, failed } = await this.generateThumbnails()

    return {
      available: true,
      added,
      updated,
      unchanged,
      orphaned: 0,
      thumbnails_generated: generated,
      thumbnails_failed: failed,
    }
  }

  /**
   * Walk the library tree returning absolute paths of every indexable file.
   * Skips the `.thumbnails/` dir and any hidden subdirs.
   */
  private async walkLibrary(): Promise<string[]> {
    const results: string[] = []

    const walk = async (dir: string): Promise<void> => {
      const entries = await fs.readdir(dir, { withFileTypes: true })
      for (const entry of entries) {
        if (entry.name.startsWith('.')) continue // skip hidden, including .thumbnails
        const full = join(dir, entry.name)
        if (entry.isDirectory()) {
          await walk(full)
        } else if (entry.isFile()) {
          const ext = extname(entry.name).toLowerCase()
          if (StlScannerService.INDEXABLE_EXTS.has(ext)) {
            results.push(full)
          }
        }
      }
    }

    await walk(StlScannerService.LIBRARY_ROOT)
    return results
  }

  /**
   * Read file size + sha256 of the first HASH_BYTES bytes. Cheap enough to
   * run on every scan; expensive enough that we DO NOT re-hash files whose
   * size hasn't changed.
   */
  private async fileInfo(absPath: string): Promise<{ size: number; hash: string }> {
    const stat = await fs.stat(absPath)
    const size = stat.size

    const hasher = createHash('sha256')
    const stream = createReadStream(absPath, { start: 0, end: StlScannerService.HASH_BYTES - 1 })
    for await (const chunk of stream) {
      hasher.update(chunk as Buffer)
    }
    const hash = hasher.digest('hex')

    return { size, hash }
  }

  /**
   * Infer the category from the file's parent directory. Users organize by
   * dropping files into category-named subdirs; anything not matching a
   * known category falls into `other` and the user fixes it via the UI.
   */
  private inferCategory(relPath: string): StlCategory {
    const parentDir = dirname(relPath).split('/')[0]
    if ((STL_CATEGORIES as readonly string[]).includes(parentDir)) {
      return parentDir as StlCategory
    }
    // Legacy directory names from before the 7→14 category rename — existing
    // installs have `tools/` and `agriculture/` folders on disk. Map them
    // forward (tools→tools-hardware, agriculture→agriculture-homestead) so a
    // file dropped straight into a legacy folder lands in the right new
    // category instead of falling to 'other'. (Uploads already use the new
    // names; this covers manual drops / `nomad stl import` into old dirs.)
    const remapped = CATEGORY_REMAP[parentDir]
    if (remapped && (STL_CATEGORIES as readonly string[]).includes(remapped)) {
      return remapped as StlCategory
    }
    return 'other'
  }

  /**
   * Insert a row, update a row that changed, or no-op for an unchanged file.
   */
  private async upsertOne(
    absPath: string,
    relPath: string
  ): Promise<'added' | 'updated' | 'unchanged'> {
    const existing = await StlFile.findBy('path', relPath)
    const stat = await fs.stat(absPath)

    if (existing) {
      // Cheap check first — if size hasn't changed, skip the hash entirely.
      if (existing.file_size_bytes === stat.size && existing.file_hash) {
        existing.last_indexed_at = DateTime.now()
        await existing.save()
        return 'unchanged'
      }

      const { size, hash } = await this.fileInfo(absPath)
      const hashChanged = existing.file_hash !== hash
      existing.file_size_bytes = size
      existing.file_hash = hash
      existing.last_indexed_at = DateTime.now()
      if (hashChanged) {
        // File contents changed — drop the old thumbnail so it regenerates.
        existing.thumbnail_path = null
        existing.thumbnail_failed = false
      }
      await existing.save()
      return 'updated'
    }

    const { size, hash } = await this.fileInfo(absPath)
    const fileExt = extname(relPath).toLowerCase()
    const row = new StlFile()
    row.path = relPath
    row.name = basename(relPath, extname(relPath))
    row.category = this.inferCategory(relPath)
    row.file_type = classifyFileType(fileExt) ?? 'stl'
    row.tags = null
    row.material = null
    row.print_time_minutes = null
    row.infill_pct = null
    row.difficulty = null
    row.description = null
    row.source_url = null
    row.license = null
    row.thumbnail_path = null
    row.thumbnail_failed = false
    row.file_size_bytes = size
    row.file_hash = hash
    row.metadata_pending = true
    row.added_at = DateTime.now()
    row.last_indexed_at = DateTime.now()
    await row.save()
    return 'added'
  }

  /**
   * Find DB rows whose paths no longer exist on disk; delete them and their
   * thumbnails. Called with the canonical on-disk path list so we don't
   * re-stat every row.
   */
  private async removeOrphans(onDiskAbsPaths: string[]): Promise<number> {
    const onDiskRelPaths = new Set(
      onDiskAbsPaths.map((p) => relative(StlScannerService.LIBRARY_ROOT, p))
    )
    const all = await StlFile.all()
    let removed = 0
    for (const row of all) {
      if (!onDiskRelPaths.has(row.path)) {
        // Best-effort thumbnail cleanup — file might already be gone if the
        // user pruned the .thumbnails dir manually.
        if (row.thumbnail_path) {
          const thumbAbs = join(StlScannerService.LIBRARY_ROOT, row.thumbnail_path)
          await fs.unlink(thumbAbs).catch(() => {})
        }
        await row.delete()
        removed++
      }
    }
    if (removed > 0) {
      logger.info(`[StlScannerService] removed ${removed} orphan row(s)`)
    }
    return removed
  }

  /**
   * Render PNG previews for any row that doesn't have one yet and hasn't
   * been marked as a sticky failure.
   *
   * Routes to the right renderer by file_type:
   *   stl   → stl-thumb binary (unchanged)
   *   pdf   → pdf2pic (first page → 256px PNG) with gm convert fallback
   *   image → sharp resize
   *   cad   → skip (no render in v1; UI shows per-type icon instead)
   *
   * If stl-thumb is missing from the image entirely (e.g., development on a
   * host where the binary isn't installed), only STL rows are marked failed —
   * pdf/image rendering is independent of stl-thumb.
   */
  private async generateThumbnails(): Promise<{ generated: number; failed: number }> {
    const pending = await StlFile.query()
      .whereNull('thumbnail_path')
      .where('thumbnail_failed', false)
    if (pending.length === 0) {
      return { generated: 0, failed: 0 }
    }

    let generated = 0
    let failed = 0

    // Probe once for stl-thumb (only relevant for stl rows).
    const stlThumbAvailable = await this.hasStlThumb()
    const stlPending = pending.filter((r) => (r.file_type ?? 'stl') === 'stl')
    if (!stlThumbAvailable && stlPending.length > 0) {
      logger.warn(
        '[StlScannerService] stl-thumb binary not found on PATH — marking ' +
          `${stlPending.length} STL thumbnail(s) as failed (Dockerfile adds it)`
      )
      for (const row of stlPending) {
        row.thumbnail_failed = true
        await row.save()
      }
      failed += stlPending.length
    }

    for (const row of pending) {
      const ft = (row.file_type ?? 'stl') as WorkshopFileType

      // CAD: no render attempt in v1 — leave thumbnail_path null and do NOT
      // set thumbnail_failed so a future scan can try again once #7 ships.
      if (ft === 'cad') continue

      // STL: already handled above when stl-thumb is missing.
      if (ft === 'stl' && !stlThumbAvailable) continue

      const result = await this.renderThumbnail(row.path, row.id, ft)
      if (result.ok) {
        row.thumbnail_path = result.thumbnailRelPath
        await row.save()
        generated++
      } else {
        row.thumbnail_failed = true
        await row.save()
        failed++
        logger.warn(
          `[StlScannerService] thumbnail failed (${ft}) on ${row.path}: ${result.error.slice(0, 200)}`
        )
      }
    }

    return { generated, failed }
  }

  private async hasStlThumb(): Promise<boolean> {
    try {
      await execFileAsync('stl-thumb', ['--version'], { timeout: 5000 })
      return true
    } catch {
      return false
    }
  }

  /**
   * Render a single thumbnail, routed by file_type.
   *
   * All paths share:
   *   • Output: {LIBRARY_ROOT}/.thumbnails/{id}.png
   *   • Timeout: 30 s (generous for large STL/PDF on ARM)
   *   • On error: returns { ok: false, error } — caller sets thumbnail_failed
   *
   * pdf2pic and sharp are lazy-imported inside this method so they don't
   * pollute the module top-level (keeps the pure tests importable without
   * those native modules).
   */
  private async renderThumbnail(
    fileRelPath: string,
    fileId: number,
    fileType: WorkshopFileType
  ): Promise<{ ok: true; thumbnailRelPath: string } | { ok: false; error: string }> {
    const inputAbs = join(StlScannerService.LIBRARY_ROOT, fileRelPath)
    const thumbName = `${fileId}.png`
    const thumbRelPath = join(StlScannerService.THUMBNAIL_DIR, thumbName)
    const thumbAbs = join(StlScannerService.LIBRARY_ROOT, thumbRelPath)

    try {
      switch (fileType) {
        case 'stl': {
          // stl-thumb args: -s 256 (size), output is positional.
          // Timeout 30s — generous for a complex 100 MB STL on Apple Silicon.
          await execFileAsync('stl-thumb', ['-s', '256', inputAbs, thumbAbs], { timeout: 30000 })
          break
        }

        case 'pdf': {
          // Use GraphicsMagick's gm convert with the Ghostscript PDF delegate.
          // This matches the stl-thumb shell-out pattern (execFile, 30s timeout)
          // and avoids awkward pdf2pic stream/path duality. ghostscript must be
          // installed (see Dockerfile — added to the apt line in this commit).
          // "[0]" selects the first page.
          await execFileAsync(
            'gm',
            ['convert', `${inputAbs}[0]`, '-resize', '256x256', '-background', 'white', '-flatten', thumbAbs],
            { timeout: 30000 }
          )
          break
        }

        case 'image': {
          // Lazy-import sharp so the pure util tests don't require native bindings.
          const sharp = (await import('sharp')).default
          await sharp(inputAbs).resize(256, 256, { fit: 'inside' }).png().toFile(thumbAbs)
          break
        }

        // cad is never passed here (filtered out in generateThumbnails).
        default:
          return { ok: false, error: `No renderer for file_type '${fileType}'` }
      }

      return { ok: true, thumbnailRelPath: thumbRelPath }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      return { ok: false, error: msg }
    }
  }
}

export interface ScanResult {
  available: boolean
  added: number
  updated: number
  unchanged: number
  orphaned: number
  thumbnails_generated: number
  thumbnails_failed: number
}
